#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Mar 16 15:31:53 CST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim debounce_tb_behav -key {Behavioral:sim_1:Functional:debounce_tb} -tclbatch debounce_tb.tcl -view /home/kafcoppelia/WORK/PKU/School/Courses/FPGADesign/PROJECTS/SimpleCPU_on_Gen2/proj/simple_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_proto_tb_behav/cpu_proto_tb_behav.wcfg -log simulate.log"
xsim debounce_tb_behav -key {Behavioral:sim_1:Functional:debounce_tb} -tclbatch debounce_tb.tcl -view /home/kafcoppelia/WORK/PKU/School/Courses/FPGADesign/PROJECTS/SimpleCPU_on_Gen2/proj/simple_cpu.sim/sim_1/behav/xsim/xsim.dir/cpu_proto_tb_behav/cpu_proto_tb_behav.wcfg -log simulate.log

